# Harmony poquito gear
- type: startingGear
  id: MobPoquitoGear
  equipment:
    ears: ClothingHeadsetService
    head: ClothingHeadHatChef
    jumpsuit: ClothingUniformJumpsuitChef
    id: PoquitoIDcard

- type: startingGear
  id: MobHermesGear
  equipment:
    ears: ClothingHeadsetCargo
    head: ClothingHeadHatBeretSeniorTechnicianHarmony
    jumpsuit: ClothingUniformTurtleneckColorLightBrown
    id: HermesIDcard
    hand: BoxFolderClipboard
