- type: entity
  parent: BaseMindRoleAntag
  id: MindRolePostOperator
  name: Listening Post Role
#  description: mind-role-post-op-description
  components:
  - type: MindRole
    antagPrototype: ListeningPost
    exclusiveAntag: true
    roleType: TeamAntagonist
  - type: ListeningPostRole

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleRecruiter
  name: Recruiter Role
  components:
  - type: MindRole
    antagPrototype: Recruiter
    exclusiveAntag: true
  - type: RecruiterRole
  - type: RoleBriefing
    briefing: recruiter-role-briefing
